repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        name: End of File Fixer
      - id: trailing-whitespace
        name: Trailing Whitespace Fixer
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        name: Terraform Formatter
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.17.0 # Get the latest from: https://github.com/terraform-docs/terraform-docs/releases
    hooks:
      - id: terraform-docs-go
        name: Generating Terraform Docs
        args:
          ["markdown", "table", "--output-file", "../README.md", "red-bucket/."]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Get the latest from: https://github.com/pre-commit/mirrors-prettier/tags
    hooks:
      - id: prettier
        name: Pretty Markdown
        args: [--prose-wrap=always]
        types_or: [markdown, yaml]
